server:
  port: 8080
  servlet:
    context-path: /springboot-file
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Cc980507
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis plus ??
mybatis-plus:
  mapper-locations: classpath*:com/example/fileproject/**/xml/*Mapper.xml
  global-config:
    # ??MP3.0???banner
    banner: false
    db-config:
      #????  0:"???ID??",1:"???????????", 2:"????ID",3:"????ID (??????ID)", 4:"????ID UUID",5:"???????ID (idWorker ??????)";
      id-type: ASSIGN_ID
      # ???????????
      table-underline: true
  configuration:
    # ?????????sql?????????????????
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ?????Map,??null?????
    call-setters-on-nulls: true
joan :
  path :
    uploadType: local
    #??????? ??
    uploadPath: D:/images/upload/

